In [1]:
import numpy as np

In [3]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.random.randint(0,100,(4,4))

array([[66, 65, 76, 66],
       [82, 74, 67, 62],
       [36, 18, 70,  4],
       [55,  7, 62, 67]])

In [5]:
a = np.ones((3,3))

In [6]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
a = np.random.randint(0,10,(3,3))

In [11]:
b = np.random.randint(0,5,(3,3))

In [12]:
a

array([[6, 6, 9],
       [1, 5, 3],
       [4, 6, 1]])

In [13]:
b

array([[1, 0, 0],
       [4, 3, 4],
       [0, 0, 1]])

In [14]:
a + b

array([[7, 6, 9],
       [5, 8, 7],
       [4, 6, 2]])

In [15]:
a - b

array([[ 5,  6,  9],
       [-3,  2, -1],
       [ 4,  6,  0]])

In [16]:
a * b

array([[ 6,  0,  0],
       [ 4, 15, 12],
       [ 0,  0,  1]])

In [17]:
a / b

C:\Users\karlw\AppData\Local\Temp\ipykernel_14232\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([[6.        ,        inf,        inf],
       [0.25      , 1.66666667, 0.75      ],
       [       inf,        inf, 1.        ]])

In [18]:
b = np.random.randint(1,5,(3,3))

In [19]:
a / b

array([[2.        , 2.        , 9.        ],
       [0.33333333, 5.        , 1.        ],
       [1.        , 3.        , 0.33333333]])

In [20]:
b

array([[3, 3, 1],
       [3, 1, 3],
       [4, 2, 3]])

In [21]:
a

array([[6, 6, 9],
       [1, 5, 3],
       [4, 6, 1]])

In [22]:
a / b

array([[2.        , 2.        , 9.        ],
       [0.33333333, 5.        , 1.        ],
       [1.        , 3.        , 0.33333333]])

In [23]:
a // b

array([[2, 2, 9],
       [0, 5, 1],
       [1, 3, 0]])

In [24]:
np.transpose(a)

array([[6, 1, 4],
       [6, 5, 6],
       [9, 3, 1]])

In [25]:
a = np.arange(1,21)

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a[0]

1

In [28]:
a[-1]

20

In [29]:
a[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [30]:
for x in a: print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
