# Numpy Notebook

In [1]:
#Import the library
import numpy as np

## Arrays vs Lists

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for i in L: print(i)

1
2
3


In [5]:
for i in A: print(i)

1
2
3


In [6]:
L.append(4)

In [7]:
A.append(4) #Static Size of arrays

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
A + np.array([5]) # Does broadcast

array([6, 7, 8])

In [10]:
A + np.array([1,2,1]) # Vector addition

array([2, 4, 4])

In [11]:
A + np.array([1,2]) # Can't add vectors of different sizes

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
2 * A

array([2, 4, 6])

In [13]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

**A Numpy array exists to do math and is different from lists in Python.**

## Dot Product

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [15]:
dot_product = 0
for i, j in zip(a,b):
    dot_product += i*j
dot_product

32

In [16]:
np.dot(a, b)

32

In [17]:
a @ b

32

### Speed Test

In [18]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 10000

# Dot product function with for loop
def dot_product(a, b):
    dot = 0
    for i, j in zip(a,b):
        dot += i*j
    return dot

# Measure time difference
t0 = datetime.now()
for _ in range(T):
    dot_product(a, b)
time_python = datetime.now() - t0

t0 = datetime.now()
for _ in range(T):
    a @ b
time_numpy = datetime.now() - t0

# Print Result
print("Python/Numpy", time_python/time_numpy)

Python/Numpy 17.571428571428573


## Matrices

In [19]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [20]:
L[0] # First row

[1, 2]

In [21]:
A = np.array([[1,2],[3,4]])
A # Formatted as an actual matrix

array([[1, 2],
       [3, 4]])

In [22]:
L[0][1]

2

In [23]:
A[0,1] # Row 1, Column 2

2

In [24]:
A[:,0] # Colon means select every

array([1, 3])

In [25]:
A.T

array([[1, 3],
       [2, 4]])

## Solving Linear Systems

In [26]:
A = np.array([[1,1], [1.5, 4]])
b = np.array([2200, 5050])

In [27]:
np.linalg.solve(A, b)

array([1500.,  700.])

## Generating Data

In [29]:
np.zeros((2, 3)) # 2 rows, 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3, 2)) # 3 rows, 2 columns

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
10 * np.ones((3, 3))

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.random() # 0-1 Distribution

0.3362808253244155

In [34]:
np.random.random((2,3))

array([[0.47132694, 0.60132168, 0.68658808],
       [0.62025162, 0.19496012, 0.23519509]])

In [35]:
np.random.randint(5, 10, (4, 4)) #low, high, size

array([[6, 5, 9, 6],
       [9, 8, 5, 9],
       [8, 6, 9, 6],
       [8, 8, 9, 6]])